### ISSUE TITLE
serverless-dynamo-stream-plugin configValidationMode: warn warning

### ISSUE THREAD

**Issue by rpinna** [commandeer/open#80] opened 2020-10-09 22:01 UTC
Thank you for writing the much-needed `serverless-dynamo-stream-plugin`  plugin.

fyi, with

`configValidationMode: warn`

serverless generates

```
Serverless: Configuration warning at 'functions['on-mutation'].events[0]': unsupported function event
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

on this version

```sh
$ .../node_modules/.bin/serverless --version
Building profileKey dev
Framework Core: 2.4.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

for this yaml

```yaml
service: conversation-message
configValidationMode: warn
frameworkVersion: '>=2.4.0'
custom:
  webpack:
    ...
package:
  individually: true
plugins:
  - serverless-webpack
  - serverless-plugin-git-variables
  - serverless-dynamo-stream-plugin
provider:
  ...
functions:
  on-mutation:
    handler: src/index.handler
    environment:
      mode: enabled
    events:
      - existingDynamoStream:
          tableName: ConversationMessage-rrx7agecrbelvawcvl7gvz2khm-dev
          streamType: NEW_AND_OLD_IMAGES
          startingPosition: LATEST
    name: conversation-message-dev-on-mutation
```

**Comment by fsproru** [comment] 2020-10-12 00:13
@rpinna thanks for submitting the issue. Just pushed a new version 0.1.5 defining the event schema if the version of Serverless supports it.

I wasn't able to reproduce it on my machine. For some reason, even the latest version of serverless npm still have the lower version of Serverless than yours.

```
Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.29.3
```

Would you mind giving 0.1.5 a shot to see if it takes care of the warning?

**Comment by fsproru** [comment] 2020-11-03 17:37
Closing since the fix went out. Let us know if you run into any issues.

**Closed by fsproru** 2020-11-03 17:37 UTC
